import { colors } from "@material-ui/core";
import {
  white,
  error,
  success,
  waiting,
  validating,
  blue,
  mediumGray,
  mainGray,
  lightBlue,
  lightGray,
  lightGreenGradient,
  lightOrange,
  mediumBlue,
  superDarkBlue,
  normalBlue,
  superLightBlue,
  blueGradient,
  yellowGradient,
  invertedYellowGradient,
  superLightGray,
  patternGreen,
  patternBlue,
  patternGray,
  waitingSigning,
  finalizing,
  approved,
  invalid,
  deleting,
  finished,
  charging,
  darkRed,
} from "./colors";

const black = "#000000";

export default {
  superLightGray,
  black,
  white,
  mediumGray,
  mainGray,
  lightBlue,
  lightGray,
  lightGreenGradient,
  blueGradient,
  lightOrange,
  mediumBlue,
  superDarkBlue,
  normalBlue,
  superLightBlue,
  yellowGradient,
  invertedYellowGradient,
  blue,
  patternBlue,
  patternGreen,
  patternGray,
  darkRed,
  primary: {
    contrastText: white,
    dark: darkRed,
    main: darkRed,
    light: darkRed,
  },
  secondary: {
    contrastText: white,
    dark: patternGreen,
    main: patternGreen,
    light: patternGreen,
  },
  error: {
    contrastText: white,
    dark: colors.red[900],
    main: colors.red[600],
    light: colors.red[400],
  },
  text: {
    primary: colors.blueGrey[900],
    secondary: colors.blueGrey[600],
    link: colors.blue[600],
  },
  link: colors.blue[800],
  icon: colors.blueGrey[600],
  background: {
    default: "#F4F6F8",
    paper: white,
  },
  divider: colors.grey[200],
  status: {
    error,
    success,
    waiting,
    validating,
    waitingSigning,
    finalizing,
    approved,
    invalid,
    deleting,
  },
  bordereauStatus: {
    error,
    waitingSigning,
    finalizing,
    charging,
    approved,
    finished,
    validating,
  },
};
